#!/usr/bin/env python3
"""SerpentStack interactive project setup.

Walks through project configuration and writes .env, Terraform,
and agent config files. Pure stdlib — no third-party dependencies.
"""

import re
import sys
from pathlib import Path

# ── ANSI helpers ──────────────────────────────────────────────

BOLD = "\033[1m"
DIM = "\033[2m"
RED = "\033[31m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
CYAN = "\033[36m"
RESET = "\033[0m"

ROOT = Path(__file__).resolve().parent.parent


def banner():
    print(f"""
{BOLD}  🐍 SerpentStack Setup{RESET}
  ──────────────────
""")


def heading(text: str):
    print(f"\n  {BOLD}─── {text} ───{RESET}\n")


def success(text: str):
    print(f"  {GREEN}✅ {text}{RESET}")


def warn(text: str):
    print(f"  {YELLOW}⚠  {text}{RESET}")


def info(text: str):
    print(f"  {DIM}{text}{RESET}")


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"  {label}{suffix}: ").strip()
    return value or default


def choose(label: str, options: list[tuple[str, str]], default: int = 1) -> int:
    """Present numbered choices. Returns 1-indexed selection."""
    print(f"  {label}")
    for i, (name, desc) in enumerate(options, 1):
        marker = " — default" if i == default else ""
        print(f"  {CYAN}[{i}]{RESET} {name}{DIM}{marker}{RESET}")
        if desc:
            print(f"      {DIM}{desc}{RESET}")
    while True:
        raw = input(f"  > ").strip()
        if not raw:
            return default
        try:
            choice = int(raw)
            if 1 <= choice <= len(options):
                return choice
        except ValueError:
            pass
        print(f"  {RED}Enter a number 1-{len(options)}{RESET}")


# ── Config collection ────────────────────────────────────────

def collect_config() -> dict:
    cfg = {}

    # Project basics
    cfg["project_name"] = prompt("Project name", "serpentstack")
    cfg["description"] = prompt("Description", "A SerpentStack application")

    # Cloud provider
    heading("Cloud Provider")
    cloud = choose("Where will you deploy?", [
        ("AWS (App Runner + RDS + ECR)", "Terraform modules included"),
        ("None (local development only)", "Skip all cloud infrastructure"),
        ("Other (I'll configure my own)", "Keep infra/ directory for customization"),
    ])
    cfg["cloud"] = ["aws", "none", "other"][cloud - 1]

    if cfg["cloud"] == "aws":
        cfg["aws_region"] = prompt("AWS Region", "us-east-1")

    # Database
    heading("Database")
    db = choose("Database setup:", [
        ("New PostgreSQL via Docker (local) + RDS (cloud)", ""),
        ("I have an existing database", ""),
    ])
    cfg["db_mode"] = "new" if db == 1 else "existing"

    if cfg["db_mode"] == "existing":
        cfg["database_url"] = prompt("Database URL", "postgresql://user:pass@host:5432/mydb")
    else:
        cfg["database_url"] = (
            f"postgresql+asyncpg://{cfg['project_name']}:{cfg['project_name']}"
            f"@localhost:5432/{cfg['project_name']}"
        )

    # Auth
    heading("Authentication")
    info("Built-in JWT auth is included (register, login, bcrypt passwords).")
    info("To swap to Clerk, Auth0, or another provider later,")
    info("see .skills/auth/SKILL.md")
    print()

    # Agent context
    heading("Agent Context")
    info("Agent context files are in .skills/ — any AI agent can read them.")
    info("Works with Claude Code, Cursor, Copilot, and any file-reading agent.")
    print()

    return cfg


# ── File writers ─────────────────────────────────────────────

def write_env(cfg: dict):
    env_path = ROOT / ".env"
    env_example = ROOT / ".env.example"

    if env_path.exists():
        overwrite = input(f"  {YELLOW}.env already exists. Overwrite? [y/N]{RESET} ").strip().lower()
        if overwrite != "y":
            info("Keeping existing .env")
            return

    lines = [
        f"# Generated by SerpentStack init",
        f"PROJECT_NAME={cfg['project_name']}",
        f"",
        f"# Database",
        f"DATABASE_URL={cfg['database_url']}",
        f"POSTGRES_USER={cfg['project_name']}",
        f"POSTGRES_PASSWORD={cfg['project_name']}",
        f"POSTGRES_DB={cfg['project_name']}",
        f"",
        f"# Application",
        f"SECRET_KEY=change-me-in-production",
        f"ENVIRONMENT=dev",
        f"LOG_LEVEL=DEBUG",
        f'CORS_ORIGINS=["http://localhost:5173"]',
    ]

    if cfg["cloud"] == "aws":
        lines += [
            f"",
            f"# AWS",
            f"AWS_REGION={cfg.get('aws_region', 'us-east-1')}",
        ]

    env_path.write_text("\n".join(lines) + "\n")
    info(f"Wrote .env")


def update_terraform(cfg: dict):
    if cfg["cloud"] != "aws":
        info("Skipping Terraform config (no cloud provider selected)")
        return

    region = cfg.get("aws_region", "us-east-1")
    name = cfg["project_name"]

    # Update environment configs
    for env_name in ["dev", "staging", "prod"]:
        tf_path = ROOT / "infra" / "environments" / env_name / "main.tf"
        if not tf_path.exists():
            continue

        content = tf_path.read_text()
        content = re.sub(
            r'project_name\s*=\s*"[^"]*"',
            f'project_name      = "{name}"',
            content,
        )
        content = re.sub(
            r'aws_region\s*=\s*"[^"]*"',
            f'aws_region        = "{region}"',
            content,
        )
        content = re.sub(
            r'bucket\s*=\s*"[^"]*-terraform-state"',
            f'bucket         = "{name}-terraform-state"',
            content,
        )
        content = re.sub(
            r'dynamodb_table\s*=\s*"[^"]*-terraform-locks"',
            f'dynamodb_table = "{name}-terraform-locks"',
            content,
        )
        tf_path.write_text(content)

    # Update root main.tf S3 backend too
    root_tf = ROOT / "infra" / "main.tf"
    if root_tf.exists():
        content = root_tf.read_text()
        content = re.sub(
            r'bucket\s*=\s*"[^"]*-terraform-state"',
            f'bucket         = "{name}-terraform-state"',
            content,
        )
        content = re.sub(
            r'dynamodb_table\s*=\s*"[^"]*-terraform-locks"',
            f'dynamodb_table = "{name}-terraform-locks"',
            content,
        )
        content = re.sub(
            r'region\s*=\s*"[^"]*"\s*\n(\s*dynamodb)',
            f'region         = "{region}"\n\\1',
            content,
        )

        # Comment out RDS module if using existing DB
        if cfg["db_mode"] == "existing":
            content = re.sub(
                r'(module "rds" \{.*?\n\})',
                lambda m: "\n".join("# " + line for line in m.group(1).splitlines()),
                content,
                flags=re.DOTALL,
            )

        root_tf.write_text(content)

    info("Updated Terraform configs")


def update_docker_compose(cfg: dict):
    dc_path = ROOT / "docker-compose.yml"
    if not dc_path.exists():
        return

    content = dc_path.read_text()
    content = content.replace("serpentstack-postgres", f"{cfg['project_name']}-postgres")
    content = content.replace("serpentstack-backend", f"{cfg['project_name']}-backend")
    content = content.replace("serpentstack-frontend", f"{cfg['project_name']}-frontend")
    content = content.replace("serpentstack-network", f"{cfg['project_name']}-network")
    dc_path.write_text(content)
    info("Updated docker-compose.yml")


def update_package_names(cfg: dict):
    """Update project name in pyproject.toml and package.json."""
    name = cfg["project_name"]

    # Backend pyproject.toml
    pyproject = ROOT / "backend" / "pyproject.toml"
    if pyproject.exists():
        content = pyproject.read_text()
        content = re.sub(
            r'^name = "serpentstack-backend"',
            f'name = "{name}-backend"',
            content,
            flags=re.MULTILINE,
        )
        content = re.sub(
            r'^description = "SerpentStack backend.*"',
            f'description = "{cfg["description"]} — backend API"',
            content,
            flags=re.MULTILINE,
        )
        pyproject.write_text(content)

    # Frontend package.json
    pkg_json = ROOT / "frontend" / "package.json"
    if pkg_json.exists():
        content = pkg_json.read_text()
        content = content.replace('"serpentstack-frontend"', f'"{name}-frontend"')
        pkg_json.write_text(content)


# ── Next steps ───────────────────────────────────────────────

def print_next_steps(cfg: dict):
    print(f"""
  {BOLD}─── Next Steps ───{RESET}

  {BOLD}Local development:{RESET}
    make setup    {DIM}# Install Python + Node dependencies{RESET}
    make dev      {DIM}# Start Postgres + backend + frontend{RESET}

  {BOLD}Your app will be running at:{RESET}
    Frontend: {CYAN}http://localhost:5173{RESET}
    Backend:  {CYAN}http://localhost:8000{RESET}
    API docs: {CYAN}http://localhost:8000/api/docs{RESET}
""")

    if cfg["cloud"] == "aws":
        print(f"""  {BOLD}Deploy to AWS (when ready):{RESET}
    {DIM}# 1. Make sure AWS CLI is configured:{RESET}
    aws configure

    {DIM}# 2. Bootstrap Terraform state (one-time):{RESET}
    make deploy-init

    {DIM}# 3. Build, push, and deploy:{RESET}
    make deploy

    {DIM}# Or do it step by step:{RESET}
    docker build -t {cfg['project_name']}-backend ./backend
    docker build -t {cfg['project_name']}-frontend ./frontend
    cd infra/environments/dev && terraform init && terraform plan
    cd infra/environments/dev && terraform apply

    {DIM}# Your app URL will be printed after deploy, or run:{RESET}
    cd infra/environments/dev && terraform output app_url
""")

    print(f"""  {BOLD}Agent context:{RESET}
    {DIM}# Skills live in .skills/ — any agent can read them{RESET}
    {DIM}# See .skills/PROJECT.md for a project overview{RESET}
    {DIM}# Point your agent at any .skills/*/SKILL.md for specific tasks{RESET}
""")


# ── Main ─────────────────────────────────────────────────────

def main():
    banner()

    cfg = collect_config()

    print()
    heading("Configuring project")

    write_env(cfg)
    update_terraform(cfg)
    update_docker_compose(cfg)
    update_package_names(cfg)

    success("Configuration complete!")

    files_updated = [".env"]
    if cfg["cloud"] == "aws":
        files_updated.append("infra/environments/")
    files_updated.append("docker-compose.yml")
    files_updated.append("backend/pyproject.toml")
    files_updated.append("frontend/package.json")

    print(f"\n  {BOLD}Files updated:{RESET}")
    for f in files_updated:
        print(f"    {f}")

    print_next_steps(cfg)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n  {DIM}Setup cancelled.{RESET}\n")
        sys.exit(1)
